---

- name: Create app directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ app_directory }}"

- name: Pull required images from docker hub
  docker_image:
    name: "{{ item }}"
    source: pull
  with_items:
    - "{{ app_docker_image }}"

- name: Create postgres db & user
  ansible.builtin.command: docker exec -it postgres /opt/scripts/create-database.sh {{ app_db_name }} {{ app_db_user }} {{ app_db_pass }}
  args:
    creates: "{{ app_directory }}/db_created_{{ app_db_name }}"

- name: Mark database creation
  ansible.builtin.file:
    path: "{{ app_directory }}/db_created_{{ app_db_name }}"
    state: touch

- name: Create rabbitmq vhosts
  ansible.builtin.command: docker exec -it rabbitmq rabbitmqctl add_vhost {{ rabbitmq_vhost_name }}
  args:
    creates: "{{ app_directory }}/rabbitmq_vhost_created_{{ rabbitmq_vhost_name }}"

- name: Mark rabbitmq vhost creation
  ansible.builtin.file:
    path: "{{ app_directory }}/rabbitmq_vhost_created_{{ rabbitmq_vhost_name }}"
    state: touch



